export const apiUrl = process.env.NODE_ENV !== "production"
? "https://onlineshoppingmarket.herokuapp.com/"
: "deploy"
export const LOCAL_TOKEN_USER = "_user"
export const LOCAL_TOKEN_NEW_PRODUCTS = "_newproduct"
export const LOCAL_TOKEN_CART_ITEM = "_cartItem "
export const LOCAL_TOKEN_NAV = "_nav "